### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by mschubert** [mschubert/clustermq#201]
This all concerns the `develop` branch and should not impact users on `master` or the stable CRAN release.

* [x] ~~`Q(... template=list(...))` does not submit jobs~~ issue with `~` expansion on log files, using `normalizePath` to avoid
* [x] ~~<kbd>Ctrl</kbd>+<kbd>c</kbd> hangs when used to interrupt polling~~ was locked in compiled code for excessive memory test, beyond the scope of this release
* [x] `multiprocess` test is "unable to terminate some child processes" (cf. e.g. https://github.com/r-lib/processx/issues/240, https://github.com/r-lib/processx/issues/236)
  * [x] https://github.com/r-lib/callr/issues/158
  * [x] ~~Test on Windows~~ can not test `multicore`, `callr` together because of https://github.com/r-lib/processx/issues/236
* [x] Consider `QSys` automatically adding log splitters (e.g. `%a` on Slurm)
* [x] Clean up doc references to `rzmq`
* [x] Make sure `qsys_impl` tests do not create logs with CRAN tests
* [x] ~~Check #199~~
* [x] #200
* [x] Manually test SSH in real setting
* [x] Clean up "run in container" docs
* [x] Check Winbuilder
* [ ] Check if PBS/Torque default log file names work

Optional

* [x] Enable logging for `multicore` (#169), `multiprocess`
* [ ] Test and document SSH from Windows (#84, #166)
* [ ] Document all available options in one place
* [x] Add *Contributing* section to README

**Comment by mschubert** [comment]
@mstr3336 I've updated the PBS scheduler to produce cmq-specific default log names, using `$PBS_ARRAY_INDEX` as per [PBS User Guide](https://www.pbsworks.com/pdfs/PBSUserGuide18.2.pdf), page 160. Can you confirm this works?

```r
remotes::install_github("mschubert/clustermq", ref="develop")
clustermq::Q(function(x) x*2, x=1:5, n_jobs=1, log_worker=T) # should create cmqXXXX-1.log in $(pwd)
```

**Comment by mstr3336** [comment]
Looks awesome, I'll test it out on the HPC soon
